### PR TITLE
Switch from HaGeZi Personal to HaGeZi Multi Normal

### PR DESCRIPTION
**Pull request by hagezi**
I have replaced the contents of the Personal with the contents of the Multi NORMAL. This contains all my personal non-aggressive blocklists and extensions.

I have adjusted the name, description and retrieval link accordingly.

Thank you,
Gerd

### CODE REVIEW

**Comment by Sergey-Lyapin** [comment]
Hello @hagezi

Could you modify metadata.json as well?

**Comment by hagezi** [comment]
@Sergey-Lyapin done

**Comment by hagezi** [comment]
@Sergey-Lyapin I have adjusted locales, where can I find the metadata.json that I should edit?

**Comment by Sergey-Lyapin** [comment]
@hagezi
These 2 files must be edited, and the name of the folder:
filter_34

`assets/filters.json` must not be edited (Sorry I didn't notice it last time)

**Comment by hagezi** [comment]
OK thanks, I overlooked that. Will close this pull request and post a clean new one.

**Pull request closed without merging**
