### PR TITLE
Add Konspiratori.sk websites Blocklist

### PR DESCRIPTION
**Pull request by LubosKadasi**
Add filter composed of [konspiratori.sk](https://konspiratori.sk/en) [websites list](https://konspiratori.sk/zoznam-stranok/en)

### CODE REVIEW

**Comment by LubosKadasi** [comment]
> What the purpose of this list?

Hello Alex,

The purpose is to have the option to block "websites that provide dubious, deceptive, fraudulent, conspiratorial, or propaganda content [1]" using AdGuard DNS blocklists.

1. - https://konspiratori.sk/en

**Comment by Alex-302** [comment]
Hm. Why they block these sites?
vigilantcitizen.com
biblik.sk
aeronet.cz
sho.sk
It looks like censorship filter. Cannot be added.

**Comment by LubosKadasi** [comment]
> Hm. Why they block these sites? ...

Each site in the list has report link. 

biblik.sk - https://konspiratori.sk/stranka/663/en
aeronet.cz - https://konspiratori.sk/stranka/665/en
sho.sk - https://konspiratori.sk/stranka/684/en
vigilantcitizen.com - https://konspiratori.sk/stranka/661/en

So it is OK to build it using hostlist-compiler and publish link in my repo?

Thank You

**Comment by Alex-302** [comment]
> Each site in the list has report link.

yes, censorship.

**Pull request closed without merging**
