### PR TITLE
Add Blocklists: HaGeZi - Multi PRO / PRO plus

### PR DESCRIPTION
**Pull request by hagezi**
Please add my Blocklist:

Multi PRO - Extended protection: https://github.com/hagezi/dns-blocklists#pro
Multi PRO plus - Maximum protection: https://github.com/hagezi/dns-blocklists#proplus

My blocklists are based on [various sources](https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md) and my own blacklists. They were designed to avoid [false positive domains](https://github.com/hagezi/dns-blocklists/blob/main/whitelist.txt) as much as possible and not to block any needed features. [Dead hosts](https://github.com/hagezi/dns-blocklists/blob/main/deadlist.txt) are regularly removed from the lists to keep them as small as possible.
They are updated and maintained daily.

For more information see the [README](https://github.com/hagezi/dns-blocklists/blob/main/README.md).

Thanks,
Gerd

### CODE REVIEW

**Comment by ameshkov** [comment]
Hello,

Thank you for the PR!

However, we would like to avoid a situation when a list duplicates lots of already included blocklists.
It seems that there's a big overlap between the sources you use and the lists that are already included in the repo.
Would it be possible to compile a version of your blocklist that does not have that overlap and add it instead?

**Comment by ameshkov** [comment]
@hagezi 

> I agree with you, one could theroetically also use the available native single sources, however one would then have to whitelist things, which I have already done for the creation of my lists, see my [whitelist](https://github.com/hagezi/dns-blocklists/blob/main/whitelist.txt).

The whitelist can be transformed into "exclusion" rules (that look like `@@||example.org^`). This way anyone who enables your blocklist in AGH/AGDNS will also automatically enable your whitelist as well. This kind of compilation will require some changes in the hostlists-compiler, but it's not much of a problem and if you agree to using this approach.

You see, the problem with a multitude of blocklists is that people tend to just enable all of them instead of sticking to a single list. You may've spent tons of time on fighting false positives and cleaning up your list, but when people just add your list on top of the ones you were cleaning up, they don't benefit from your work. If we convert the whitelist + personal to the adblock-style syntax the way I propose, enabling your blocklist in AdGuard Home or AdGuard DNS will actually make a difference.

**Comment by hagezi** [comment]
@ameshkov 

Thanks for the quick feedback. I understand your point of view. I create a personal black + whitelist and make it available.

**Comment by hagezi** [comment]
@ameshkov 
Here you can find the compiled version of the discussed list, please look over it. It is automatically updated daily if there are changes in one of the source lists.

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal-blackwhite.txt

JSON:

```
{
    "name": "HaGeZi's Personal Black- & Whitelist",
    "description": "An extension for existing blocklists, my personal black and whitelist. Unblocks false positives and referral domains.",
    "homepage": "https://github.com/hagezi/dns-blocklists",
    "license": "https://github.com/hagezi/dns-blocklists/blob/main/LICENSE.md",
    "sources": [
        {
            "name": "HaGeZi's Personal DNS Blocklist",
            "source": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt",
            "type": "adblock",
            "transformations": ["RemoveModifiers", "Validate"]
        },
        {
            "name": "HaGeZi's White-/Allowlist",
            "source": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist.txt",
            "type": "adblock",
            "transformations": ["Validate"]
        },
        {
            "name": "HaGeZi's Referral White-/Allowlist",
            "source": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt",
            "type": "adblock",
            "transformations": ["Validate"]
        }
    ],
    "transformations": [
        "Compress",
        "Deduplicate"
    ]
}
```

**Comment by hagezi** [comment]
@ameshkov I close this pull request and create a new one for Personal Black & White.

**Pull request closed without merging**
