### PR TITLE
Add The Blocklist Project - Ads List

### PR DESCRIPTION
**Pull request by Sergey-Lyapin**
https://github.com/AdguardTeam/HostlistsRegistry/issues/155

### CODE REVIEW

**Comment by ameshkov** [comment]
Is this an auto-generated list?

Also, check this:
https://github.com/AdguardTeam/HostlistsRegistry/issues/82#issuecomment-1339547379

**Comment by Sergey-Lyapin** [comment]
> Is this an auto-generated list?

How to find it out?

**Comment by ameshkov** [comment]
Check the repo commits history, check how many issues are there.

Generally, carefully check if the list satisfies the requirements from here:
https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here

**Review by ameshkov — APPROVED** [review]

**Review by Alex-302 — APPROVED** [review]

**Comment by ameshkov** [comment]
I don't get it guys, the list is clearly maintained not well, why are we adding it?

https://github.com/blocklistproject/Lists/commits/master

**Pull request merged**
