### PR TITLE
Create GOODBYEADS

### PR DESCRIPTION
**Pull request by Padge007**
This is not my ads list i am merely suggesting it to be added it belongs to this guy

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiRncjypP2BAxWN8LsIHcnWCFEQFnoECBsQAQ&url=https%3A%2F%2Fgithub.com%2Fjerryn70%2FGoodbyeAds&usg=AOvVaw1Xe7NAj-ZiusPGDLXiOAes&opi=89978449

### CODE REVIEW

**Comment by Alex-302** [comment]
Just a compilation of filters. We prefer original lists.

**Comment by Padge007** [comment]
No problem it was just suggested to me that's all it's actually been added to Blokada and NextDNS 🤷‍♂️

**Comment by Alex-302** [comment]
We already have many of that filters.

**Comment by Alex-302** [comment]
Better report about missed ads:)

**Comment by Padge007** [comment]
lol while you're here Alex is there a way of installing the certificate needed for HTTPS filtering on my shield without root access?

**Comment by Alex-302** [comment]
No, you cannot copy the cert to the system storage without root access.

**Pull request closed without merging**
