### PR TITLE
New filters

### PR DESCRIPTION
**Pull request by Spl0itable**
Have added filters for no amazon, facebook, microsoft, and tiktok

### CODE REVIEW

**Comment by Spl0itable** [comment]
I'm hoping to use these blocklists with adguard-dns.io 🤓 thanks

**Comment by Alex-302** [comment]
If you want to block FB, no need to add all subdomains.
Instead of 6k rules with `fbcdn.net` can be used `||fbcdn.net^`

**Comment by Spl0itable** [comment]
@Alex-302 sorry I should have called it "Meta" as it includes all Meta properties (Facebook, Instagram, messenger, etc)

**Comment by Alex-302** [comment]
@Spl0itable it is just HOSTS list, where `0.0.0.0` replaced by `||`. 99% of rules are redundant.

**Comment by Alex-302** [comment]
In AG, thouthands of rules can be replaced by 
```
||facebook.com^
||fb.me^
||fb.com^
||messenger.com^
||fbsbx.com^
||tfbnw.net^
||oculusvr.com^
||fbcdn.net^
||instagram.com^
||whatsapp.net^
||facebook.net^
||oculus.com^
||whatsapp.com^
||giphy.com^
||facebookmail.com^
||fbcdn.com^
||fbcdn-*.akamaihd.net^
||facebookbrand.com^
||facebook.de^
||facebook.design^
||facebook.fr^
||facebookvirtualassistant.com^
||freebasics.com^
||fbpigeon.com^
||internet.org^
||instagramstatic-*.akamaihd.net.edgesuite.net^
||instagramstatic-*.akamaihd.net^
||facebook-web-clients.appspot.com^
||facebookdesktop.com^
||giphy.map.fastly.net^
||fbexternal-a.akamaihd.net^
||fbstatic-a.akamaihd.net^
||block-test-facebook.developerdan.com^
||block-test.developerdan.com^
||calibra.com^
||fbcallback.wechat.com^
||fburl.com^
||giphyscripts.s3.amazonaws.com^
||m.me^
||static.addtoany.com^
||static.hootsuite.com^
||wa.me^
||watchdog.energized.pro^

@@||platform.foursquare.com^! Not owned by FB
@@||static.licdn.com^! Not owned by FB
```

**Comment by Spl0itable** [comment]
@Alex-302 ok thanks. That could still be useful to create a list for no Meta. It wasn't my list originally, it's one I pulled from a different source.

**Comment by Spl0itable** [comment]
@Alex-302 ok, will do. How about the other lists?

**Comment by Spl0itable** [comment]
@Alex-302  I didn't just make suggestions, I went out of my way to submit a PR. These were only for Big Tech. No need to be condescending, when I'm just tying to help...

**Comment by Alex-302** [comment]
New filters should be added one per pool-request.
Checking a large PR will take more time.

**Pull request closed without merging**
