### PR TITLE
Added HBO Max as blockable service

### PR DESCRIPTION
**Pull request by sandervankasteel**
HBO Max was used to be known as HBO Now / HBO Go.

### CODE REVIEW

**Review by Sergey-Lyapin — APPROVED** [review]

**Comment by Sergey-Lyapin** [comment]
Hello @sandervankasteel

May I ask where you get the list of domains?

**Comment by sandervankasteel** [comment]
> Hello @sandervankasteel
> 
> May I ask where you get this list of domains?

Ofcourse, I got it from https://www.netify.ai/resources/applications/hbo.

**Comment by Sergey-Lyapin** [comment]
@sandervankasteel 
Please use this compressed SVG instead, I decided to replace it after all.

```
<svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\" viewBox=\"0 0 50 50\"><path d=\"M0 14v22h5v-9h3v9h5V14H8v8H5v-8H0zm15 0v22h8.4c3.1 0 5.7-2.3 6.2-5.4a11 11 0 1 0 0-11.2c-.5-3-3-5.4-6.2-5.4H15zm5 5h3a2 2 0 1 1 0 4h-3v-4zm19 0a6 6 0 1 1 0 12 6 6 0 0 1 0-12zm0 2a4 4 0 0 0-4 4 4 4 0 0 0 4 4 4 4 0 0 0 4-4 4 4 0 0 0-4-4zm-11 2.8v2.4c-.4-.5-1-1-2-1.2 1-.3 1.7-.8 2-1.3zm-8 4h3a2 2 0 1 1 0 4h-3v-4z\"/></svg>
```

**Comment by sandervankasteel** [comment]
> @sandervankasteel Please use this compressed SVG instead, I decided to replace it after all.
> 
> ```
> <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\" viewBox=\"0 0 50 50\"><path d=\"M0 14v22h5v-9h3v9h5V14H8v8H5v-8H0zm15 0v22h8.4c3.1 0 5.7-2.3 6.2-5.4a11 11 0 1 0 0-11.2c-.5-3-3-5.4-6.2-5.4H15zm5 5h3a2 2 0 1 1 0 4h-3v-4zm19 0a6 6 0 1 1 0 12 6 6 0 0 1 0-12zm0 2a4 4 0 0 0-4 4 4 4 0 0 0 4 4 4 4 0 0 0 4-4 4 4 0 0 0-4-4zm-11 2.8v2.4c-.4-.5-1-1-2-1.2 1-.3 1.7-.8 2-1.3zm-8 4h3a2 2 0 1 1 0 4h-3v-4z\"/></svg>
> ```

Icon is updated! Just out of curiosity, which SVG minifier / compressor did you use?

**Comment by Sergey-Lyapin** [comment]
@sandervankasteel 
I use this:
https://jakearchibald.github.io/svgomg/
Reduce "number precision" to the minimum value at which the icon is not distorted.

**Review by ameshkov — APPROVED** [review]

**Review by Alex-302 — APPROVED** [review]

**Comment by krystian3w** [comment]
In future just "Max" after end fusion Discovery with HBO.

**Pull request merged**
