### PR TITLE
Replace @@ with denyallow

### PR DESCRIPTION
**Pull request by KnightmareVIIVIIXC**
Change @@||discord.gift to modifier: ||discord*.gift^$denyallow=discord.gift. Tested and working.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
1) The OP is probably in the wrong repo.
2) https://github.com/AdguardTeam/HostlistsRegistry/blob/main/filters/security/filter_12_DandelionSproutsAntiMalwareList/filter.txt shows it became supported 2 or 3 weeks ago.
3) I don't currently see a problem with `@@||discord.gift^`. Even in the event that someone really doesn't like the Discord platform, `||discord.gift^$important` in custom entries would've sufficed.

**Comment by hagezi** [comment]
> 2) https://github.com/AdguardTeam/HostlistsRegistry/blob/main/filters/security/filter_12_DandelionSproutsAntiMalwareList/filter.txt shows it became supported 2 or 3 weeks ago.

Thanks for pointing that out, I had overlooked it.

**Comment by KnightmareVIIVIIXC** [comment]
My way of thinking is to safe guard against potential future threats. For example, if sub.discord.gift becomes malicious and the ||discord*.gift^$denyallow=discord.gift rule is used, then the user will be safe; if you leave the @@||discord.gift^ rule, then the dangerous sub.discord.gift will be processed even if the user adds the rule ||sub.discord.gift^.

**Comment by ameshkov** [comment]
> However, Denyallow is not currently supported by the hostlist compiler. Rules with Denyallow are not adopted.

Why, it is supported:
https://github.com/AdguardTeam/HostlistCompiler/blob/f8559b02ee1730b6493e5aa57a9551222a6beda5/src/transformations/validate.js#L15

**Comment by DandelionSprout** [comment]
Support was only added a few weeks ago, so I supposed the word spread widely out yet.

**Pull request closed without merging**
