### PR TITLE
Some translate Fix

### PR DESCRIPTION
**Pull request by hacamer**

### CODE REVIEW

**Comment by ameshkov** [comment]
@hacamer hi! Lists metadata should be translated via Crowdin:
https://crowdin.com/project/adguard-applications/content/files

`miscellaneous/hostlists-registry`

**Comment by hacamer** [comment]
ok, thx

**Comment by hacamer** [comment]
@ameshkov oh no, I can't visit it. It say `We are sorry, but you do not have access to this page or resource for some reason.`
image

**Comment by ameshkov** [comment]
@hacamer oh, probably that page is admin-only.

Try this one: https://crowdin.com/project/adguard-applications/

You should be able to navigate files there as well.

**Comment by hacamer** [comment]
thx



---Original---
From: "Andrey ***@***.***&gt;
Date: Mon, May 30, 2022 01:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AdguardTeam/HostlistsRegistry] Some translate Fix (PR #40)




 
@hacamer oh, probably that page is admin-only.
 
Try this one: https://crowdin.com/project/adguard-applications/
 
You should be able to navigate files there as well.

**Pull request closed without merging**
