### PR TITLE
Add Call of Duty as a blockable service

### PR DESCRIPTION
**Pull request by Sergey-Lyapin**
https://github.com/AdguardTeam/HostlistsRegistry/issues/256

### CODE REVIEW

**Comment by Alex-302** [comment]
I think better block developer/publisher/distributor instead of every game one by one.

**Comment by Sergey-Lyapin** [comment]
@ameshkov what do you think about it? ^

**Comment by Alex-302** [comment]
> Parents usually know the name of the game, not its developer btw.

In this PR blocked few games
https://github.com/AdguardTeam/HostlistsRegistry/pull/260

**Comment by Sergey-Lyapin** [comment]
So we have to choose to block:

Only games
Only developers
Games and developers at the same time

**Pull request closed without merging**
